server:
  port: 9007

spring:
  application:
    name: catupload
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 0
      location: temp
  resources:
    chain:
      cache: false
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/





